server:
  port: 8099
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/backend
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: movie.exchange
    queue: movie.queue
    routingkey: movie.routingkey
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: true
      registerWithEureka: true
