server:
  port: 8099
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/BackExamen
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: true
      registerWithEureka: true
