server:
  port: 8097
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: root
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: true
      registerWithEureka: true
      
app:
  message: Message has been sent Successfully..

queue:
  movie:
    name: MovieQueue
    
message: Hola!

