server:
  port: 8097
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: root
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    exchange: movie.exchange
    queue: movie.queue
    routingkey: movie.routingkey
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: true
      registerWithEureka: true
      
app:
  message: Message has been sent Successfully..

resilience4j:
  circuitbreaker:
    instances:
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      movies:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
          
 management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: microservice course
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}
