server:
  port: 8097
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: root
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: true
      registerWithEureka: true
      
queue:
  movie:
    name: MovieQueue

message: hello world

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}
      
