server:
   port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/backend
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    #exchange2: series.exchange
    #queue2: series.queue
    #routingkey2: series.routingkey  
eureka:
   client:
     fetchRegistry: true
     registerWithEureka: true
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
      
message: Hola desde Series Service!

queue:
  movie:
    name: SerieQueue

