server:
   port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/BackExamen
eureka:
   client:
     fetchRegistry: true
     registerWithEureka: true
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
