server:
   port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://series-service:27017/backend
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672 
    
eureka:
   client:
     fetchRegistry: true
     registerWithEureka: true
   serviceUrl:
     defaultZone: http://config-service:8761/eureka 

queue:
  serie:
    name: SerieQueue

